# permissions for end users to edit dkronoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dkronoperator-editor-role
rules:
- apiGroups:
  - operator.github.com
  resources:
  - dkronoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.github.com
  resources:
  - dkronoperators/status
  verbs:
  - get
